version: '2'

services:
  student-enrollments:
    image: 'arielgpaz/student-enrollments:1.0.0'
    build:
      context: .
    container_name: student-enrollments
    ports:
      - '8080:8080'
    depends_on:
      - se_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://se_db:3306/se_db
      - SPRING_DATASOURCE_USERNAME=se_db_user
      - SPRING_DATASOURCE_PASSWORD=se_db_2024
      - FLYWAY_URL=jdbc:mysql://se_db:3306/se_db
    networks:
      - my-network

  se_db:
    image: "mysql:8.0"
    container_name: se_db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=se_db
      - MYSQL_USER=se_db_user
      - MYSQL_PASSWORD=se_db_2024
      - MYSQL_ROOT_PASSWORD=se_db_2024
    networks:
      - my-network

networks:
    my-network:
      driver: bridge
