spring:
  application:
    name: student-enrollments

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/student-registrations-db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
