spring:
  application:
    name: student-enrollments
  datasource:
    url: jdbc:mysql://localhost:3306/se_db?allowPublicKeyRetrieval=true
    username: se_db_user
    password: se_db_2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

